---
- name: Migrate AWX Job Templates to AAP (single or bulk)
  hosts: pilotserver
  gather_facts: no
  vars:
    awx_host: "{{ survey_awx_host }}"
    awx_token: "{{ survey_awx_token }}"
    aap_host: "{{ survey_aap_host }}"
    aap_token: "{{ survey_aap_token }}"
    organization_id: "{{ survey_aap_organization_id }}"
    # Set this to the AWX API ID to migrate just one JT; leave blank to run bulk.
    template_id: "{{ survey_template_id | default('') }}"
    include_regex: "{{ survey_include_regex | default('') }}"
    exclude_regex: "{{ survey_exclude_regex | default('') }}"
    verify_tls: "{{ survey_verify_tls | default(false) }}"
    dry_run: "{{ survey_dry_run | default(false) }}"

  tasks:
    - name: Ensure migrator is present
      ansible.builtin.copy:
        src: files/migrate_job_templates.py
        dest: ./migrate_job_templates.py
        mode: '0755'

    - name: Run JT migration (single/bulk; force EE id and Machine cred id)
      ansible.builtin.command:
        argv:
          - python3
          - ./migrate_job_templates.py
          - --awx-host
          - "{{ awx_host }}"
          - --awx-token
          - "{{ awx_token }}"
          - --aap-host
          - "{{ aap_host }}"
          - --aap-token
          - "{{ aap_token }}"
          - --organization-id
          - "{{ organization_id }}"
          - --force-ee-id
          - "{{ force_ee_id | default(5) | int }}"
          - --force-machine-cred-id
          - "{{ force_machine_cred_id | default(31) | int }}"
          # single vs bulk
          {% set has_tid = ((template_id | default('') | string | length) > 0) %}
          {% for item in ( has_tid | ternary(['--template-id', (template_id | string)], ['--all']) ) %}
          - "{{ item }}"
          {% endfor %}
          # include
          {% set has_inc = ((include_regex | default('') | string | length) > 0) %}
          {% for item in ( has_inc | ternary(['--include', include_regex], []) ) %}
          - "{{ item }}"
          {% endfor %}
          # exclude
          {% set has_exc = ((exclude_regex | default('') | string | length) > 0) %}
          {% for item in ( has_exc | ternary(['--exclude', exclude_regex], []) ) %}
          - "{{ item }}"
          {% endfor %}
          # dry-run
          {% for item in ( (dry_run | default(false) | bool) | ternary(['--dry-run'], []) ) %}
          - "{{ item }}"
          {% endfor %}
          # verify-tls
          {% for item in ( (verify_tls | default(false) | bool) | ternary(['--verify-tls'], []) ) %}
          - "{{ item }}"
          {% endfor %}
          no_log: false