---
- name: Migrate AWX Job Templates to AAP (single or bulk)
  hosts: pilotserver
  gather_facts: no
  vars:
    awx_host: "{{ survey_awx_host }}"
    awx_token: "{{ survey_awx_token }}"
    aap_host: "{{ survey_aap_host }}"
    aap_token: "{{ survey_aap_token }}"
    organization_id: "{{ survey_aap_organization_id }}"
    # Set this to the AWX API ID to migrate just one JT; leave blank to run bulk.
    template_id: "{{ survey_template_id | default('') }}"
    include_regex: "{{ survey_include_regex | default('') }}"
    exclude_regex: "{{ survey_exclude_regex | default('') }}"
    verify_tls: "{{ survey_verify_tls | default(false) }}"
    dry_run: "{{ survey_dry_run | default(false) }}"

  tasks:
    - name: Ensure migrator is present
      ansible.builtin.copy:
        src: files/migrate_job_templates.py
        dest: ./migrate_job_templates.py
        mode: '0755'

    - name: Build argv for JT migrator (YAML-compliant)
      ansible.builtin.set_fact:
        jt_args: >-
          {{
            [
              'python3', './migrate_job_templates.py',
              '--awx-host', awx_host,
              '--awx-token', awx_token,
              '--aap-host', aap_host,
              '--aap-token', aap_token,
              '--organization-id', (organization_id | string),
              '--force-ee-id', ((force_ee_id | default(5) | int) | string),
              '--force-machine-cred-id', ((force_machine_cred_id | default(31) | int) | string)
            ]
            +
            (
              ['--template-id', (template_id | string)]
              if (template_id | default('') | string | length) > 0 else
              ['--all']
            )
            +
            (
              ['--include', include_regex]
              if (include_regex | default('') | string | length) > 0 else
              []
            )
            +
            (
              ['--exclude', exclude_regex]
              if (exclude_regex | default('') | string | length) > 0 else
              []
            )
            +
            (
              ['--dry-run'] if (dry_run | default(false) | bool) else []
            )
            +
            (
              ['--verify-tls'] if (verify_tls | default(false) | bool) else []
            )
          }}

    - name: Run JT migration (single/bulk; force EE id and Machine cred id)
      ansible.builtin.command:
        argv: "{{ jt_args }}"
      no_log: false