---
- name: Export AWX environment from Kubernetes
  hosts: localhost
  gather_facts: no
  vars:
    awx_env: test
    export_filename: "awx_export_{{ awx_env }}.json"
    awx_host: "{{ groups['awx_' + awx_env][0] }}"
    awx_namespace: "awx"

  tasks:
    - name: Create exports/ dir on control node (task container)
      ansible.builtin.file:
        path: "exports"
        state: directory
        mode: "0755"
      become: false

    - name: Get AWX pod name
      ansible.builtin.shell: |
        kubectl get pods -n {{ awx_namespace }} -l "app.kubernetes.io/component=task" -o jsonpath="{.items[0].metadata.name}"
      register: awx_pod
      delegate_to: "{{ awx_host }}"
      become: true

    - name: Export AWX data using awx-manage inside the pod
      ansible.builtin.shell: |
        kubectl exec -n {{ awx_namespace }} {{ awx_pod.stdout }} -- \
          awx-manage export > /tmp/{{ export_filename }}
      delegate_to: "{{ awx_host }}"
      become: true

    - name: Fetch exported AWX data to control node
      ansible.builtin.fetch:
        src: "/tmp/{{ export_filename }}"
        dest: "exports/{{ export_filename }}"
        flat: yes
      delegate_to: "{{ awx_host }}"
      become: false

    - name: Confirm export fetched successfully
      ansible.builtin.stat:
        path: "exports/{{ export_filename }}"
      register: export_status
      become: false

    - name: Show result
      ansible.builtin.debug:
        msg: "AWX export was saved to: exports/{{ export_filename }}"
      when: export_status.stat.exists
